### ISSUE TITLE
Improve The Plant Recognition

### ISSUE THREAD

**Issue by ghost** [Pflanzy/Pflanzy-mobile-app#111]

**Comment by eminaydin** [comment]
It takes up to 10 seconds to take a picture which is quite annoying. Can we try to change the functionality so that it takes the picture as soon as user clicks the button and process happens afterwards? Because otherwise we have to hold camera all the time.

**Comment by ghost** [comment]
> It takes up to 10 seconds to take a picture which is quite annoying. Can we try to change the functionality so that it takes the picture as soon as user clicks the button and process happens afterwards? Because otherwise we have to hold camera all the time.

yeah I already skipped the processing and saving the picture to the local storage for plant recognition . it still takes time but faster than before for sure . It should be already merged.
