### ISSUE TITLE
Redux Store

### ISSUE THREAD

**Issue by ghost** [Pflanzy/Pflanzy-mobile-app#52]

**Comment by oliverwebr** [comment]
Regarding firebase, i created a small example in #56 
It would be good to think about which data needs to be available globally, as mentioned redux just for managing the user would be too much.

**Comment by oliverwebr** [comment]
If we go with redux we might just dispatch our actions from within the convenience functions
https://github.com/Pflanzy/Pflanzy-mobile-app/blob/dcd316dff3c492bac009bc22f5ee5e23841a602a/firebase/index.js#L5-L7

**Comment by oliverwebr** [comment]
Redux example  #58
